/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "brand-purple": "#7C3AED",
        "brand-purple-dim": "rgba(124,58,237,0.15)",
        "surface-card": "#161622",
        "app-bg": "#0D0D13",
        "input-bg": "#111118",
        "muted": "#9CA3AF",
        "caption": "#6B7280",
        "on-surface": "#dee2ed",
        "on-error": "#690005",
        "surface-container-high": "#252a32",
        "surface-tint": "#b5c4ff",
        "on-background": "#dee2ed",
        "tertiary-container": "#e96c1f",
        "inverse-primary": "#0d52dd",
        "primary-fixed": "#dce1ff",
        "on-secondary": "#3f008e",
        "background": "#0f141b",
        "tertiary": "#ffb692",
        "surface-container-low": "#171c23",
        "outline": "#8d90a0",
        "surface-dim": "#0f141b",
        "surface-container-lowest": "#090e16",
        "primary": "#b5c4ff",
        "outline-variant": "#434655",
        "secondary": "#d2bbff",
        "inverse-surface": "#dee2ed",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary-container": "#4b1b00",
        "on-primary-fixed-variant": "#003cad",
        "secondary-container": "#6001d1",
        "tertiary-fixed-dim": "#ffb692",
        "surface-container": "#1b2028",
        "surface-bright": "#343942",
        "on-secondary-fixed": "#25005a",
        "on-secondary-container": "#c9aeff",
        "on-secondary-fixed-variant": "#5a00c6",
        "secondary-fixed-dim": "#d2bbff",
        "primary-container": "#648aff",
        "surface-container-highest": "#30353d",
        "on-tertiary-fixed": "#341100",
        "on-surface-variant": "#c3c5d7",
        "surface": "#0f141b",
        "secondary-fixed": "#eaddff",
        "on-error-container": "#ffdad6",
        "surface-variant": "#30353d",
        "on-primary-container": "#00236c",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#b5c4ff",
        "inverse-on-surface": "#2c3139",
        "on-primary-fixed": "#00164d",
        "on-tertiary-fixed-variant": "#793000",
        "on-primary": "#00297b",
        "on-tertiary": "#562000"
      },
      spacing: {
        stack_lg: "24px",
        margin_desktop: "40px",
        gutter: "16px",
        margin_mobile: "20px",
        stack_md: "16px",
        base: "4px",
        container_max_width: "600px",
        stack_sm: "8px"
      },
      fontFamily: {
        h1: ["Outfit", "sans-serif"],
        "mono-label": ["JetBrains Mono", "monospace"],
        display: ["Outfit", "sans-serif"],
        body: ["Outfit", "sans-serif"],
        h2: ["Outfit", "sans-serif"],
        caption: ["Outfit", "sans-serif"],
        "display-mobile": ["Outfit", "sans-serif"]
      },
      fontSize: {
        h1: ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "mono-label": ["12px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" }],
        display: ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        body: ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["18px", { lineHeight: "1.4", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "display-mobile": ["30px", { lineHeight: "1.2", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
